[package]
name = "AoC"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "aoc_2021_01"
path = "src/AoC-2021-01.rs"

[[bin]]
name = "aoc_2021_02"
path = "src/AoC-2021-02.rs"